apiVersion: v1
kind: Service
metadata:
  name: w-tasky-svc
  namespace: w-test
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: w-tasky
